[package]
name = "grepbot"
version = "1.0.0"
authors = ["Neil Ashford <ashfordneil0@gmail.com>"]

[dependencies]
serenity = "0.5.1"
log = "0.4.1"
fern = "0.5.5"
serde = "1.0.37"
mvdb = "0.2.1"
serde_json = "1.0.13"
chrono = "0.4.1"
regex = "0.2.10"
